# **************************************************************************** #
#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: damerica <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/03 19:36:43 by damerica          #+#    #+#              #
#    Updated: 2019/09/04 19:45:03 by damerica         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
OBJ = ft_display_file.c
OBJ0 = ft_display_file.o

all : $(NAME)

$(NAME):

	gcc -Wall -Werror -Wextra -c $(OBJ) 
	gcc -Wall -Werror -Wextra -o $(NAME)  $(OBJ0)
clean:
	/bin/rm -f $(OBJ0)

fclean: clean
	/bin/rm -f $(NAME)
